# Generated by Django 5.0.6 on 2024-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_audience_created_at_doctor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=8),
        ),
    ]
