# Generated by Django 5.0.6 on 2024-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_doctor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coummunity/images'),
        ),
    ]
