# Generated by Django 5.0.6 on 2024-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_audience_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='community/images'),
        ),
    ]
