# Generated by Django 5.0.6 on 2024-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_hub/images'),
        ),
    ]
