# Generated by Django 5.0.6 on 2024-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0003_article_recommendedbydoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
