# Generated by Django 5.0.6 on 2024-05-22 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0004_testimonial_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Personal_Story',
        ),
    ]
