# Generated by Django 5.0.6 on 2024-05-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_hub', '0005_rename_testimonial_personal_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_hub/images')),
                ('personal_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content_hub.personal_story')),
            ],
        ),
    ]
